#cloud-config
hostname: boot
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    primary-group: ubuntu
    groups: users, admin
    lock_passwd: false
    shell: /bin/bash
    # password = "ubuntu"
    passwd: "$6$rounds=4096$1IdWhyNg1$PXQGbjAa5OVPrKq0O2R6h3jN02RF5OowmKDYVVbKQTIwe3Pvv7wwXGKduOkaKEeO.tbe7hHjA2Zpc.9JsAN.i."

write_files:
  - path: /etc/ssh/sshd_config
    content: |
      Protocol 2

  - path: /etc/dnsmasq.conf
    content: |
      log-queries
      log-dhcp
      interface=ens3
      enable-tftp
      tftp-root=/var/lib/dnsmasq
      dhcp-range=set:ens3,172.16.0.12,172.16.0.15
      dhcp-option=tag:ens3,option:router,172.16.0.1
      dhcp-match=set:efi32,option:client-arch,6
      dhcp-boot=tag:efi32,ipxe.efi
      dhcp-match=set:efibc,option:client-arch,7
      dhcp-boot=tag:efibc,ipxe.efi
      dhcp-match=set:efi64,option:client-arch,9
      dhcp-boot=tag:efi64,ipxe.efi
      dhcp-userclass=set:ipxe,iPXE
      dhcp-boot=tag:ipxe,http://172.16.0.11/ipxe

  # create a directory
  - path: "/var/lib/dnsmasq/.dummy"

  - path: /var/www/html/ipxe
    content: |
      #!ipxe
      chain http://172.16.0.11/ipxe.${serial}

  - path: /var/www/html/ipxe.1234abcd
    content: |
      #!ipxe
      kernel http://172.16.0.11/coreos_production_pxe.vmlinuz coreos.first_boot=1 coreos.config.url=http://172.16.0.11/ign.${serial} coreos.autologin=ttyS0 console=ttyS0
      initrd http://172.16.0.11/coreos_production_pxe_image.cpio.gz
      boot

  - path: /var/www/html/ign.1234abcd
    content: |
      {
        "ignition": {"version": "2.3.0"},
        "storage": {"files": [{"filesystem": "root", "path": "/etc/hostname", "mode": 420, "contents": {"source": "data:,worker-1"}}]},
        "networkd": {"units": [{"name": "00-eth0.network", "contents": "[Match]\nName=eth0\n\n[Network]\nAddress=172.16.0.101"}]}
      }

  - path: /var/www/html/ipxe.5678efgh
    content: |
      #!ipxe
      kernel http://172.16.0.11/coreos_production_pxe.vmlinuz coreos.first_boot=1 coreos.config.url=http://172.16.0.11/ign.${serial} coreos.autologin=ttyS0 console=ttyS0
      initrd http://172.16.0.11/coreos_production_pxe_image.cpio.gz
      boot

  - path: /var/www/html/ign.5678efgh
    content: |
      {
        "ignition": {"version": "2.3.0"},
        "storage": {"files": [{"filesystem": "root", "path": "/etc/hostname", "mode": 420, "contents": {"source": "data:,worker-2"}}]},
        "networkd": {"units": [{"name": "00-eth0.network", "contents": "[Match]\nName=eth0\n\n[Network]\nAddress=172.16.0.102"}]}
      }

  - path: /etc/resolv.conf
    content: |
      nameserver 8.8.8.8

runcmd:
  - [ systemctl, stop, systemd-resolved.service ]
  - [ systemctl, disable, systemd-resolved.service ]
  - [ systemctl, enable, dnsmasq.service ]
  - [ systemctl, start, dnsmasq.service ]
  - [ systemctl, enable, nginx.service ]
  - [ systemctl, start, nginx.service ]
  - [ curl, -sSL, -o, /var/lib/dnsmasq/ipxe.efi, "http://boot.ipxe.org/ipxe.efi" ]
  - [ curl, -sSL, -o, /var/www/html/coreos_production_pxe.vmlinuz, "https://stable.release.flatcar-linux.net/amd64-usr/2605.12.0/flatcar_production_pxe.vmlinuz" ]
  - [ curl, -sSL, -o, /var/www/html/coreos_production_pxe_image.cpio.gz, "https://stable.release.flatcar-linux.net/amd64-usr/2605.12.0/flatcar_production_pxe_image.cpio.gz" ]

packages:
  - dnsmasq
  - nginx
