name: CI
on:
  pull_request:
  push:
    branches:
      - 'main'
defaults:
  run:
    working-directory: v2
env:
  go-version: 1.15
jobs:
  test:
    name: Small test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - run: make setup
      - run: make test
        timeout-minutes: 10
      - run: make test-dcnet
        timeout-minutes: 10
      - run: make test-vm
        timeout-minutes: 10
  e2e:
    name: End-to-end Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Run e2e test on GCP instance
        run: ../bin/run-mtest.sh
      - name: Set the instance lifetime
        run: |
          . ../bin/env
          $GCLOUD compute instances add-metadata ${INSTANCE_NAME} --zone ${ZONE} \
            --metadata shutdown-at=$(date -Iseconds -d+30minutes)
        if: failure()
