name: CI
on:
  pull_request:
  push:
    branches:
      - 'main'
defaults:
  run:
    working-directory: v2
env:
  go-version: 1.15
jobs:
  test:
    name: Small test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - run: make setup
      - run: make test
      - run: make test-dcnet
      - run: make test-vm
